spring:
  application:
    name: event-ingestion-service
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  kafka:
    raw-topic: raw-events
